#!/bin/bash

if [ -z "$1" ]; then
   month=$(date +%m) 
else
   month=$1  
fi

__fname=Fatura-`printf %d%02d $(date +%Y) $((10#$month))`.pdf
_encrypt="/disks/W/Financeiro/Cartões/Mastercard/Faturas/$__fname"

if [ ! -f "$_encrypt" ]; then
  echo -e "\n No such file: \033[38;5;124m" $_encrypt "\033[0m\n"

else
  _decrypt="/disks/W/Financeiro/Cartões/Mastercard/Faturas/_$__fname"

  qpdf --decrypt --password=$(cat /disks/W/Secret_Files/submarino | head -n1) "$_encrypt"  "$_decrypt"
  rm "$_encrypt"
  mv "$_decrypt" "$_encrypt"
fi
