#!/bin/bash

find /disks/W/Financeiro -regex ".*$(date +%Y).*_\.pdf" |
  awk 'BEGIN { 
    FS = "\\n" 
    RS = ""
  };
  {
    print "\n"
    for (i=1; i<=NF; i++) {
      match($i, /[^\/]+.[^\/]+$/, arr)
      print "  \033[38;5;10m" arr[0]
      print "   \033[38;5;238m└── \033[38;5;59m" $i "\033[0m"
    }
    print "\n"
  }' $1
