#!/bin/bash

if [[ ! -z "$1" ]]; then
  _year=$1
  if [[ "${#_year}" -eq 4 ]]; then
    year=$_year
    shift 1
  else
    year=$(date +%Y)
  fi

   month=$1
else
  year=$(date +%Y)
  month=$(date +%m)
fi

find /disks/W/Financeiro -regex ".*`printf %d $year`[-._]?`printf %02d $((10#$month))`.*_\.\(pdf\|html\|jpg\|png\)" |
  awk 'BEGIN {
    FS = "\\n"
    RS = ""
  };
  {
    print "\n"
    for (i=1; i<=NF; i++) {
      match($i, /[^\/]+.[^\/]+$/, arr)
      print "  \033[38;5;10m" arr[0]
      print "   \033[38;5;238m└── \033[38;5;59m" $i "\033[0m"
    }
    print "\n"
  }' $2
