#!/bin/bash

#https://wiki.archlinux.org/index.php/Touchpad_Synaptics
#ftp://www.x.org/pub/X11R7.5/doc/man/man4/synaptics.4.html

synclient TouchpadOff=1

synclient CircScrollDelta=0.2
synclient CircScrollTrigger=3
synclient CircularScrolling=1
synclient CoastingSpeed=10
synclient EmulateTwoFingerMinW=50
synclient EmulateTwoFingerMinZ=100
synclient FingerHigh=30
synclient FingerLow=25
synclient HorizEdgeScroll=1
synclient PalmDetect=1
synclient PalmMinWidth=5
synclient PalmMinZ=10
synclient PressureMotionMinZ=40
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient VertTwoFingerScroll=1

